## Diana Volynsky & Ximena Javadpour
## Sources:
## Source for battleship code help https://erlerobotics.gitbooks.io/erle-robotics-learning-python-gitbook-free/content/exercisebattleship/battleship.html
## Source for boat inspiration https://www.youtube.com/watch?v=S21p1EwNgA8
## Source for turtle.write instructions https://pythonguides.com/python-turtle-write-function/
import random
print("Welcome to Battleship!")

import turtle
t= turtle
t.speed(100)
t.setup(800, 500)

t.bgcolor("lightblue")

t.penup()
t.goto(-400, -150)
t.pendown()
t.color("navy")
t.begin_fill()
for i in range(2):
    t.forward(800)
    t.right(90)
    t.forward(100)
    t.right(90)
t.end_fill()

t.penup()
t.goto(-400, -80)
t.pendown()
t.color("peru")
t.begin_fill()
t.right(45)
t.forward(100)
t.left(45)
t.forward(250)
t.left(45)
t.forward(100)
t.end_fill()
t.penup()

t.right(45)
t.goto(10, -80)
t.pendown()
t.color("burlywood")
t.begin_fill()
t.right(45)
t.forward(100)
t.left(45)
t.forward(250)
t.left(45)
t.forward(100)
t.end_fill()

t.penup()
t.goto(-200, -80)
t.pendown()
t.color("sienna")
t.begin_fill()
t.left(45)
for i in range(2):
    t.forward(200)
    t.left(90)
    t.forward(10)
    t.left(90)
t.end_fill()

t.right(45)
t.penup()
t.goto(210, -80)
t.pendown()
t.color("sienna")
t.begin_fill()
t.left(45)
for i in range(2):
    t.forward(200)
    t.left(90)
    t.forward(10)
    t.left(90)
t.end_fill()

t.penup()
t.goto(-200, 120)
t.pendown()
t.color("thistle")
t.begin_fill()
t.right(130)
t.forward(250)
t.right(140)
t.forward(190)
t.end_fill()

t.penup()
t.forward(14)
t.pendown()
t.begin_fill()
t.forward(180)
t.right(139)
t.forward(240)
t.end_fill()
t.penup()

t.left(49)
t.penup()
t.goto(210, 120)
t.pendown()
t.color("lightcoral")
t.begin_fill()
t.right(130)
t.forward(250)
t.right(140)
t.forward(190)
t.end_fill()

t.penup()
t.forward(14)
t.pendown()
t.begin_fill()
t.forward(180)
t.right(139)
t.forward(240)
t.end_fill()
t.penup()
t.goto(0,110)
t.color("ghostwhite")
t.write("WELCOME TO BATTLESHIP", font = ("Bradley Hand", 57, 'bold'), align ="center")



gameBoard = []
for x in range (0,7):
    gameBoard.append(["O"]*7)
def boardFormat(gameBoard):
    for row in gameBoard:
        print(" ".join(row))
boardFormat(gameBoard)
def row(gameBoard):
    from random import randint 
    return randint (0,7)
def column(gameBoard):
    from random import randint 
    return randint (0,7)
shipRow=row(gameBoard)
shipCol=column(gameBoard)

for turns in range(5):
    guessR = int(input("What row is my battleship in?:"))
    guessC = int(input("What column is my battleship in?:"))
    if guessR==shipRow and guessC==shipCol:
        print ("Good job! You sank my ship!")
        t.right(41)
        t.clear()
        t.bgcolor("lightblue")
        t.penup()
        t.goto(-400, -150)
        t.pendown()
        t.color("navy")
        t.begin_fill()
        for i in range(2):
            t.forward(800)
            t.right(90)
            t.forward(100)
            t.right(90)
        t.end_fill()
        t.penup()

        t.goto(10, -80)
        t.pendown()
        t.color("burlywood")
        t.begin_fill()
        t.right(45)
        t.forward(100)
        t.left(45)
        t.forward(250)
        t.left(45)
        t.forward(100)
        t.end_fill()

        t.penup()
        t.goto(210, -80)
        t.pendown()
        t.color("sienna")
        t.begin_fill()
        t.left(45)
        for i in range(2):
            t.forward(200)
            t.left(90)
            t.forward(10)
            t.left(90)
        t.end_fill()
 
        t.penup()
        t.goto(-200, 10)
        t.pendown()
        t.color("black")
        t.begin_fill()
        t.right(130)
        t.forward(250)
        t.right(140)
        t.forward(190)
        t.end_fill()

        t.penup()
        t.forward(14)
        t.pendown()
        t.begin_fill()
        t.forward(180)
        t.right(139)
        t.forward(240)
        t.end_fill()
        t.penup()

        t.left(49)
        t.penup()
        t.goto(210, 120)
        t.pendown()
        t.color("lightcoral")
        t.begin_fill()
        t.right(130)
        t.forward(250)
        t.right(140)
        t.forward(190)
        t.end_fill()

        t.penup()
        t.forward(14)
        t.pendown()
        t.begin_fill()
        t.forward(180)
        t.right(139)
        t.forward(240)
        t.end_fill()
        t.penup()
        t.goto(0,160)
        t.color("ghostwhite")
        t.write("CONGRATULATIONS", font = ("Bradley Hand", 70, 'bold'), align ="center")
        t.goto(0,100)
        t.write("You win!", font = ("Bradley Hand", 60, 'bold'), align ="center")
    else:
        if guessR not in range(7) or guessC not in range(7):
            print("Bad input, try again.")
        elif gameBoard[guessR][guessC]=="X":
            print("You already tried that one, try again please.")
        else:
            print("Sorry, you missed. Try again.")
            gameBoard[guessR][guessC]="X"
    if turns == 4:
        print("Sorry, you lost. Game over!")
        t.clear()
        t.right(41)
        t.bgcolor("dimgrey")
        t.penup()
        t.goto(-400, -150)
        t.pendown()
        t.color("black")
        t.begin_fill()
        for i in range(2):
            t.forward(800)
            t.right(90)
            t.forward(100)
            t.right(90)
        t.end_fill()
        t.penup()

        t.goto(10, -80)
        t.pendown()
        t.color("burlywood")
        t.begin_fill()
        t.right(45)
        t.forward(100)
        t.left(45)
        t.forward(250)
        t.left(45)
        t.forward(100)
        t.end_fill()

        t.penup()
        t.goto(210, -80)
        t.pendown()
        t.color("saddlebrown")
        t.begin_fill()
        t.left(45)
        for i in range(2):
            t.forward(200)
            t.left(90)
            t.forward(10)
            t.left(90)
        t.end_fill()

        t.penup()
        t.goto(-200, 10)
        t.pendown()
        t.color("grey")
        t.begin_fill()
        t.right(130)
        t.forward(250)
        t.right(140)
        t.forward(190)
        t.end_fill()

        t.penup()
        t.forward(14)
        t.pendown()
        t.begin_fill()
        t.forward(180)
        t.right(139)
        t.forward(240)
        t.end_fill()
        t.penup()

        t.left(49)
        t.penup()
        t.goto(210, 120)
        t.pendown()
        t.color("lightsteelblue")
        t.begin_fill()
        t.right(130)
        t.forward(250)
        t.right(140)
        t.forward(190)
        t.end_fill()

        t.penup()
        t.forward(14)
        t.pendown()
        t.begin_fill()
        t.forward(180)
        t.right(139)
        t.forward(240)
        t.end_fill()
        t.penup()
        t.goto(0,160)
        t.color("ghostwhite")
        t.write("GAME OVER", font = ("Bradley Hand", 70, 'bold'), align ="center")
        t.goto(0,100)
        t.write("You lose", font = ("Bradley Hand", 60, 'bold'), align ="center")
    boardFormat(gameBoard)


    
